# Generated by Django 5.2.3 on 2025-06-21 00:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Titulo do Serviço')),
                ('slug', models.SlugField(default='no-name', verbose_name='Tipo (slug)')),
                ('specialty', models.CharField(max_length=124, null=True, verbose_name='Especialidade')),
                ('estimated_time', models.TimeField(verbose_name='Tempo de Execução')),
                ('is_it_home', models.BooleanField(verbose_name='É à Domicilio?')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_span', models.TimeField(verbose_name='Tempo Estimado')),
                ('start_time', models.DateTimeField(verbose_name='Horário de Início do Serviço')),
                ('end_time', models.DateTimeField(verbose_name='Horário de Término do Serviço')),
                ('client_requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_client', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
                ('worker_responsible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_worker', to=settings.AUTH_USER_MODEL, verbose_name='Colaborador')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor_pet_app.task', verbose_name='Serviço')),
            ],
        ),
    ]
